# Generated by Django 5.1.11 on 2025-11-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_assigned_to_lead_estimated_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='general_notes',
        ),
    ]
