# Generated by Django 5.1.11 on 2025-11-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_general_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='account_medsos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
