# Generated by Django 5.2.3 on 2025-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalitem',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='debit',
            field=models.IntegerField(default=0),
        ),
    ]
