# Generated by Django 5.2.3 on 2025-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_rename_name_account_account_name_remove_account_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
