# Generated by Django 5.2.2 on 2025-06-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_journalentry_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
