# Generated by Django 5.2.2 on 2025-10-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_journalitem_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
    ]
