# Generated by Django 5.2.2 on 2025-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_journalentry_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='period',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
