# Generated by Django 5.2.2 on 2025-10-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_journalentry_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closingperiod',
            options={},
        ),
    ]
