# Generated by Django 5.2.2 on 2025-10-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_closingperiod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closingperiod',
            options={'ordering': ['-period']},
        ),
    ]
