# Generated by Django 5.2.2 on 2025-10-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_closingperiod_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='period',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
