# Generated by Django 5.1.11 on 2025-11-15 05:35

import apps.careers.file_validation_field
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('cover', models.ImageField(upload_to='job', verbose_name='Upload cover')),
                ('description', models.TextField(verbose_name='Description')),
                ('jobtype', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship'), ('4', 'Remote'), ('5', 'Freelance')], max_length=10, verbose_name='JobType')),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='LastDate')),
                ('filled', models.BooleanField(default=False, verbose_name='Filled')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Salary')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('vacancies', models.PositiveIntegerField(default=0, verbose_name='Number of Vaccencies')),
                ('status', models.CharField(choices=[('p', 'Published'), ('d', 'Draft Box'), ('r', 'Recycle Bin')], default='p', max_length=1, verbose_name='Job status')),
                ('stick', models.CharField(choices=[('y', 'Sticky'), ('n', 'Do not top')], default='n', max_length=1, verbose_name='Whether sticky')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CreatedBy')),
            ],
            options={
                'verbose_name': 'Add Job',
                'verbose_name_plural': 'Add Job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('fullname', models.CharField(max_length=100, verbose_name='Fullname')),
                ('cover', models.ImageField(upload_to='job/coverphoto/', verbose_name='Upload cover')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tenth_percent', models.FloatField(verbose_name='Tenth Percent')),
                ('puc_or_diploma', models.CharField(choices=[('p', 'Puc'), ('d', 'Diploma')], default='d', max_length=1, verbose_name='College')),
                ('puc_or_diploma_marks', models.FloatField(verbose_name='Puc or Diploma Marks')),
                ('board', models.CharField(max_length=60, verbose_name='Board')),
                ('degree_college', models.CharField(max_length=50, verbose_name='Degree College')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('university', models.CharField(max_length=50, verbose_name='University')),
                ('branch', models.CharField(max_length=50, verbose_name='Branch')),
                ('grade_or_percent', models.CharField(choices=[('g', 'Grade'), ('p', 'Percentage')], default='g', max_length=1, verbose_name='Degree Marks Format')),
                ('degree_marks', models.FloatField(verbose_name='Degree Marks')),
                ('github', models.URLField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Url must be entered in the format: 'https://github.com/xxx or https://www.github.com/xxx '. Up to 15 digits allowed.", regex='^https:\\/\\/[a-z]{2,3}\\.github\\.com\\/.*$')], verbose_name='Github Url')),
                ('linkedin', models.URLField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'https://linkedin.com/in/xxx or https://www.linkedin.com/in/xxx'. Up to 15 digits allowed.", regex='^https:\\/\\/[a-z]{2,3}\\.linkedin\\.com\\/.*$')], verbose_name='Linkedin Url')),
                ('resume', apps.careers.file_validation_field.ContentTypeRestrictedFileField(help_text='Attach resume with .docx or .pdf format', upload_to='documents/%Y/%m/%d', verbose_name='Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CreatedBy')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.job', verbose_name='Job Selected')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AppliedOn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='careers.job', verbose_name='Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Category',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='jobcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.jobcategory', verbose_name='Job_Category'),
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Job Location',
                'verbose_name_plural': 'Job Location',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.joblocation', verbose_name='Job_Location'),
        ),
    ]
