# Generated by Django 5.1.11 on 2025-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('command', models.CharField(max_length=2000, verbose_name='command')),
                ('describe', models.CharField(max_length=300, verbose_name='description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='createdaAt')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'Commands',
                'verbose_name_plural': 'Commands',
            },
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailto', models.CharField(max_length=300, verbose_name='Emailto')),
                ('title', models.CharField(max_length=2000, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('send_result', models.BooleanField(default=False, verbose_name='send result')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
            options={
                'verbose_name': 'Email Sendlog',
                'verbose_name_plural': 'Email Sendlog',
                'ordering': ['-created_time'],
            },
        ),
    ]
