# Generated by Django 5.2.2 on 2025-06-05 13:00

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_stage', models.CharField(choices=[('awareness', 'Awareness'), ('interest', 'Interest'), ('desire', 'Desire'), ('action', 'Action'), ('retention', 'Retention')], max_length=20, verbose_name='Funnel Stage')),
                ('kategori_biaya', models.CharField(max_length=100, verbose_name='Kategori Biaya')),
                ('tanggal_posting', models.DateField(default=datetime.date.today)),
                ('rencana_tanggal_posting', models.DateField(blank=True, null=True)),
                ('jenis_konten', models.CharField(max_length=100, verbose_name='Jenis Konten')),
                ('tujuan', models.CharField(max_length=255, verbose_name='Tujuan')),
                ('judul', ckeditor.fields.RichTextField(verbose_name='Judul')),
                ('metode_pengukuran', models.CharField(max_length=255, verbose_name='Metode Pengukuran')),
                ('as_at_6_12_jam_impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions (6-12 Jam)')),
                ('as_at_6_12_jam_member_reached', models.PositiveIntegerField(default=0, verbose_name='Member Reached (6-12 Jam)')),
                ('as_at_6_12_jam_view', models.PositiveIntegerField(default=0, verbose_name='View (6-12 Jam)')),
                ('as_at_6_12_jam_email_send', models.PositiveIntegerField(default=0, verbose_name='Email Send (6-12 Jam)')),
                ('as_at_6_12_jam_email_open_rate', models.FloatField(default=0.0, verbose_name='Email Open Rate (6-12 Jam)')),
                ('as_at_6_12_jam_reactions_like', models.PositiveIntegerField(default=0, verbose_name='Reactions / Like (6-12 Jam)')),
                ('as_at_6_12_jam_comment', models.PositiveIntegerField(default=0, verbose_name='Comment (6-12 Jam)')),
                ('as_at_6_12_jam_repost_share', models.PositiveIntegerField(default=0, verbose_name='Repost / Share (6-12 Jam)')),
                ('as_at_24_jam_impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions (24 Jam)')),
                ('as_at_24_jam_member_reached', models.PositiveIntegerField(default=0, verbose_name='Member Reached (24 Jam)')),
                ('as_at_24_jam_view', models.PositiveIntegerField(default=0, verbose_name='View (24 Jam)')),
                ('as_at_24_jam_email_send', models.PositiveIntegerField(default=0, verbose_name='Email Send (24 Jam)')),
                ('as_at_24_jam_email_open_rate', models.FloatField(default=0.0, verbose_name='Email Open Rate (24 Jam)')),
                ('as_at_24_jam_reactions_like', models.PositiveIntegerField(default=0, verbose_name='Reactions / Like (24 Jam)')),
                ('as_at_24_jam_comment', models.PositiveIntegerField(default=0, verbose_name='Comment (24 Jam)')),
                ('as_at_24_jam_repost_share', models.PositiveIntegerField(default=0, verbose_name='Repost / Share (24 Jam)')),
                ('as_at_3hari_impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions (3 Hari)')),
                ('as_at_3hari_member_reached', models.PositiveIntegerField(default=0, verbose_name='Member Reached (3 Hari)')),
                ('as_at_3hari_view', models.PositiveIntegerField(default=0, verbose_name='View (3 Hari)')),
                ('as_at_3hari_email_send', models.PositiveIntegerField(default=0, verbose_name='Email Send (3 Hari)')),
                ('as_at_3hari_email_open_rate', models.FloatField(default=0.0, verbose_name='Email Open Rate (3 Hari)')),
                ('as_at_3hari_reactions_like', models.PositiveIntegerField(default=0, verbose_name='Reactions / Like (3 Hari)')),
                ('as_at_3hari_comment', models.PositiveIntegerField(default=0, verbose_name='Comment (3 Hari)')),
                ('as_at_3hari_repost_share', models.PositiveIntegerField(default=0, verbose_name='Repost / Share (3 Hari)')),
                ('as_at_1minggu_impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions (1 Minggu)')),
                ('as_at_1minggu_member_reached', models.PositiveIntegerField(default=0, verbose_name='Member Reached (1 Minggu)')),
                ('as_at_1minggu_view', models.PositiveIntegerField(default=0, verbose_name='View (1 Minggu)')),
                ('as_at_1minggu_email_send', models.PositiveIntegerField(default=0, verbose_name='Email Send (1 Minggu)')),
                ('as_at_1minggu_email_open_rate', models.FloatField(default=0.0, verbose_name='Email Open Rate (1 Minggu)')),
                ('as_at_1minggu_reactions_like', models.PositiveIntegerField(default=0, verbose_name='Reactions / Like (1 Minggu)')),
                ('as_at_1minggu_comment', models.PositiveIntegerField(default=0, verbose_name='Comment (1 Minggu)')),
                ('as_at_1minggu_repost_share', models.PositiveIntegerField(default=0, verbose_name='Repost / Share (1 Minggu)')),
                ('lama_jam', models.PositiveIntegerField(default=0, verbose_name='Lama (Jam)')),
                ('follower', models.PositiveIntegerField(default=0, verbose_name='Follower')),
                ('discovery', models.PositiveIntegerField(default=0, verbose_name='Discovery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
