# Generated by Django 5.2.2 on 2025-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedin',
            name='for_who',
            field=models.CharField(blank=True, choices=[('sdmportabel', 'Sdmportabel'), ('personal', 'Personal'), ('data_tech_nusantara', 'Data_Tech_Nusantara')], max_length=20, null=True, verbose_name='For Who'),
        ),
    ]
