# Generated by Django 5.2.2 on 2025-06-07 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0002_linkedin_for_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='tanggal_posting',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
