# Generated by Django 5.2.2 on 2025-06-07 15:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0003_alter_linkedin_tanggal_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='judul',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Judul'),
        ),
    ]
