# Generated by Django 5.2.2 on 2025-06-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0006_rename_for_who_blog_for_market_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='for_market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post_media.market'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ig',
            name='for_market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post_media.market'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkedin',
            name='for_market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post_media.market'),
            preserve_default=False,
        ),
    ]
