# Generated by Django 5.2.2 on 2025-06-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0007_market_alter_blog_for_market_alter_ig_for_market_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='metode_pengukuran',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tujuan',
        ),
        migrations.RemoveField(
            model_name='ig',
            name='metode_pengukuran',
        ),
        migrations.RemoveField(
            model_name='ig',
            name='tujuan',
        ),
        migrations.RemoveField(
            model_name='linkedin',
            name='metode_pengukuran',
        ),
        migrations.RemoveField(
            model_name='linkedin',
            name='tujuan',
        ),
    ]
