# Generated by Django 5.2.2 on 2025-06-12 11:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0008_remove_blog_metode_pengukuran_remove_blog_tujuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Judul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ig',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Judul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedin',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Judul'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='judul',
            field=models.CharField(max_length=100, verbose_name='judul'),
        ),
        migrations.AlterField(
            model_name='ig',
            name='judul',
            field=models.CharField(max_length=100, verbose_name='judul'),
        ),
        migrations.AlterField(
            model_name='linkedin',
            name='judul',
            field=models.CharField(max_length=100, verbose_name='judul'),
        ),
    ]
