# Generated by Django 5.2.2 on 2025-06-12 11:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0009_blog_isi_konten_ig_isi_konten_linkedin_isi_konten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='ig',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='linkedin',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Judul'),
        ),
    ]
