# Generated by Django 5.2.2 on 2025-06-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0012_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ig',
            name='for_market',
        ),
        migrations.RemoveField(
            model_name='linkedin',
            name='for_market',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='IG',
        ),
        migrations.DeleteModel(
            name='LinkedIn',
        ),
    ]
