# Generated by Django 5.2.2 on 2025-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0013_remove_ig_for_market_remove_linkedin_for_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='akun',
            field=models.CharField(choices=[('personal', 'Personal'), ('sdmportabel', 'Instagram'), ('datatech', 'DataTech')], default=1, max_length=20, verbose_name='channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.CharField(choices=[('blog', 'Blog'), ('ig', 'Instagram'), ('thread', 'Thread'), ('linkedin', 'linkedin')], max_length=20, verbose_name='channel'),
        ),
    ]
