# Generated by Django 5.2.2 on 2025-06-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0014_channel_akun_alter_channel_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='akun',
            field=models.CharField(choices=[('personal', 'Personal'), ('sdmportabel', 'Instagram'), ('datatech', 'DataTech')], max_length=20, verbose_name='akun'),
        ),
    ]
