# Generated by Django 5.2.2 on 2025-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0015_alter_channel_akun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='akun',
            field=models.CharField(choices=[('personal', 'Personal'), ('sdmportabel', 'sdmportabel'), ('datatech', 'DataTech')], max_length=20, verbose_name='akun'),
        ),
    ]
