# Generated by Django 5.2.2 on 2025-08-25 14:23

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0016_alter_channel_akun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.CharField(choices=[('personal', 'Personal'), ('sdmportabel', 'sdmportabel'), ('datatech', 'DataTech')], max_length=20)),
                ('ChannelSimple', models.CharField(choices=[('blog', 'Blog'), ('ig', 'Instagram'), ('thread', 'Thread'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('funnel_stage', models.CharField(choices=[('awareness', 'Awareness'), ('interest', 'Interest'), ('desire', 'Desire'), ('action', 'Action'), ('retention', 'Retention')], max_length=20)),
                ('kategori_biaya', models.CharField(max_length=100)),
                ('tanggal_posting', models.DateTimeField(default=django.utils.timezone.now)),
                ('rencana_tanggal_posting', models.DateField(blank=True, null=True)),
                ('jenis_konten', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=100)),
                ('isi_konten', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('lama_jam', models.PositiveIntegerField(default=0)),
                ('follower', models.PositiveIntegerField(default=0)),
                ('discovery', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_media.market')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('6_12_jam', '6-12 Jam'), ('24_jam', '24 Jam'), ('3_hari', '3 Hari'), ('1_minggu', '1 Minggu')], max_length=20)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('member_reached', models.PositiveIntegerField(default=0)),
                ('view', models.PositiveIntegerField(default=0)),
                ('email_send', models.PositiveIntegerField(default=0)),
                ('email_open_rate', models.FloatField(default=0.0)),
                ('reactions_like', models.PositiveIntegerField(default=0)),
                ('comment', models.PositiveIntegerField(default=0)),
                ('repost_share', models.PositiveIntegerField(default=0)),
                ('ChannelSimple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='post_media.channelsimple')),
            ],
        ),
    ]
