# Generated by Django 5.2.2 on 2025-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0017_channelsimple_channelmetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmetric',
            old_name='ChannelSimple',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='channelmetric',
            name='lama_jam',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
