# Generated by Django 5.2.2 on 2025-08-25 16:02

from django.db import migrations

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0019_remove_channelmetric_lama_jam_and_more'),
    ]

    operations = [
        migrations.RunPython(noop),
    ]
