# Generated by Django 5.2.2 on 2025-08-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0020_remove_channelmetric_lama_jam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmetric',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='channelmetric',
            name='updated_at',
        ),
    ]
