# Generated by Django 5.2.2 on 2025-08-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0021_remove_channelmetric_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelsimple',
            old_name='ChannelSimple',
            new_name='channel_type',
        ),
        migrations.AlterUniqueTogether(
            name='channelmetric',
            unique_together={('channel', 'period')},
        ),
    ]
