# Generated by Django 5.2.2 on 2025-08-25 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0022_rename_channelsimple_channelsimple_channel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsimple',
            name='lama_jam',
        ),
        migrations.AddField(
            model_name='channelmetric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='channelmetric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsimple',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsimple',
            name='tanggal_posting',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='channelsimple',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
