# Generated by Django 5.2.2 on 2025-10-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0023_remove_channelsimple_lama_jam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmetric',
            name='lama_jam',
        ),
    ]
