# Generated by Django 5.2.2 on 2025-10-19 12:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0024_remove_channelmetric_lama_jam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsimple',
            name='for_market',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_comment',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_email_open_rate',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_email_send',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_impressions',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_member_reached',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_reactions_like',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_repost_share',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_3hari_view',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_comment',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_email_open_rate',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_email_send',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_impressions',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_member_reached',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_reactions_like',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_repost_share',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_6_12_jam_view',
        ),
        migrations.AddField(
            model_name='channel',
            name='custom_metrics',
            field=models.JSONField(blank=True, default=dict, help_text="Tambahkan metrik tambahan seperti 'conversion', 'profile_visit', 'click_through', dll.", null=True, verbose_name='Metrik Khusus / Custom Metrics'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.CharField(choices=[('blog', 'Blog'), ('ig', 'Instagram'), ('thread', 'Thread'), ('linkedin', 'LinkedIn')], max_length=20, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Isi Konten'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='judul',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.DeleteModel(
            name='ChannelMetric',
        ),
        migrations.DeleteModel(
            name='ChannelSimple',
        ),
    ]
