# Generated by Django 5.2.2 on 2025-10-19 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0025_remove_channelsimple_for_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_comment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Comment (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_email_open_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Email Open Rate (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_email_send',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Email Send (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_impressions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Impressions (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_member_reached',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Member Reached (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_reactions_like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Reactions / Like (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_repost_share',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Repost / Share (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_1minggu_view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='View (1 Minggu)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_comment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Comment (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_email_open_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Email Open Rate (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_email_send',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Email Send (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_impressions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Impressions (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_member_reached',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Member Reached (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_reactions_like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Reactions / Like (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_repost_share',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Repost / Share (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='as_at_24_jam_view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='View (24 Jam)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='tanggal_posting',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
