# Generated by Django 5.2.2 on 2025-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0026_alter_channel_as_at_1minggu_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='discovery',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Discovery'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='follower',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Follower'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='lama_jam',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Lama (Jam)'),
        ),
    ]
