# Generated by Django 5.2.2 on 2025-10-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0027_alter_channel_discovery_alter_channel_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
