# Generated by Django 5.2.2 on 2025-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0028_channel_is_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='akun',
            field=models.CharField(choices=[('personal', 'Personal'), ('sdmportabel', 'Sdmportabel'), ('teknusa', 'Teknusa')], max_length=20, verbose_name='akun'),
        ),
    ]
