# Generated by Django 5.2.2 on 2025-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0029_alter_channel_akun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='tanggal_posting',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
