# Generated by Django 5.2.2 on 2025-10-24 11:24

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0030_alter_channel_tanggal_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_comment',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_email_open_rate',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_email_send',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_impressions',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_member_reached',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_reactions_like',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_repost_share',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_1minggu_view',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_comment',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_email_open_rate',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_email_send',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_impressions',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_member_reached',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_reactions_like',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_repost_share',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='as_at_24_jam_view',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='custom_metrics',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='discovery',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='lama_jam',
        ),
        migrations.AlterField(
            model_name='channel',
            name='akun',
            field=models.CharField(choices=[('personal', 'Personal'), ('sdmportabel', 'Sdmportabel'), ('teknusa', 'Teknusa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.CharField(choices=[('ig', 'Instagram'), ('threads', 'Threads'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('blog', 'Blog')], max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='funnel_stage',
            field=models.CharField(choices=[('awareness', 'Awareness'), ('interest', 'Interest'), ('desire', 'Desire'), ('action', 'Action'), ('retention', 'Retention')], max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='isi_konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='jenis_konten',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='judul',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kategori_biaya',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ChannelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('24h', '24 Jam'), ('1w', '1 Minggu'), ('1m', '1 Bulan')], max_length=10)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='post_media.channel')),
            ],
        ),
    ]
