# Generated by Django 5.2.2 on 2025-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_media', '0031_remove_channel_as_at_1minggu_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.CharField(choices=[('ig', 'Instagram'), ('threads', 'Threads'), ('linkedin', 'LinkedIn'), ('linkedin_newsletter', 'LinkedIn Newsletter'), ('linkedin_company', 'LinkedIn Company'), ('tiktok', 'TikTok'), ('blog', 'Blog')], max_length=20),
        ),
    ]
